In [1]:
!pip install fastf1

Collecting fastf1
  Downloading fastf1-3.8.1-py3-none-any.whl.metadata (5.1 kB)
Requirement already satisfied: cryptography in /usr/local/lib/python3.12/dist-packages (from fastf1) (43.0.3)
Requirement already satisfied: matplotlib<4.0.0,>=3.8.0 in /usr/local/lib/python3.12/dist-packages (from fastf1) (3.10.0)
Requirement already satisfied: numpy<3.0.0,>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from fastf1) (2.0.2)
Requirement already satisfied: pandas<3.0.0,>=2.1.1 in /usr/local/lib/python3.12/dist-packages (from fastf1) (2.2.2)
Requirement already satisfied: platformdirs in /usr/local/lib/python3.12/dist-packages (from fastf1) (4.9.4)
Requirement already satisfied: pydantic in /usr/local/lib/python3.12/dist-packages (from fastf1) (2.12.3)
Requirement already satisfied: pyjwt in /usr/local/lib/python3.12/dist-packages (from fastf1) (2.11.0)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.12/dist-packages (from fastf1) (2.9.0.post0)
Collecting rapidfuzz (from fastf1)
  Downloading rapidfuzz-3.14.3-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (12 kB)
Collecting requests-cache>=1.0.0 (from fastf1)
  Downloading requests_cache-1.3.1-py3-none-any.whl.metadata (9.4 kB)
Requirement already satisfied: requests>=2.30.0 in /usr/local/lib/python3.12/dist-packages (from fastf1) (2.32.4)
Requirement already satisfied: scipy<2.0.0,>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from fastf1) (1.16.3)
Collecting signalrcore (from fastf1)
  Downloading signalrcore-1.0.2-py3-none-any.whl.metadata (13 kB)
Collecting timple>=0.1.6 (from fastf1)
  Downloading timple-0.1.8-py3-none-any.whl.metadata (2.0 kB)
Requirement already satisfied: websockets>=10.3 in /usr/local/lib/python3.12/dist-packages (from fastf1) (15.0.1)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4.0.0,>=3.8.0->fastf1) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4.0.0,>=3.8.0->fastf1) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4.0.0,>=3.8.0->fastf1) (4.62.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4.0.0,>=3.8.0->fastf1) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4.0.0,>=3.8.0->fastf1) (26.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4.0.0,>=3.8.0->fastf1) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4.0.0,>=3.8.0->fastf1) (3.3.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<3.0.0,>=2.1.1->fastf1) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<3.0.0,>=2.1.1->fastf1) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil->fastf1) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.30.0->fastf1) (3.4.5)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.30.0->fastf1) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.30.0->fastf1) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.30.0->fastf1) (2026.2.25)
Requirement already satisfied: attrs>=21.2 in /usr/local/lib/python3.12/dist-packages (from requests-cache>=1.0.0->fastf1) (25.4.0)
Collecting cattrs>=22.2 (from requests-cache>=1.0.0->fastf1)
  Downloading cattrs-26.1.0-py3-none-any.whl.metadata (8.5 kB)
Collecting url-normalize>=2.0 (from requests-cache>=1.0.0->fastf1)
  Downloading url_normalize-2.2.1-py3-none-any.whl.metadata (5.6 kB)
Requirement already satisfied: cffi>=1.12 in /usr/local/lib/python3.12/dist-packages (from cryptography->fastf1) (2.0.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic->fastf1) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic->fastf1) (2.41.4)
Requirement already satisfied: typing-extensions>=4.14.1 in /usr/local/lib/python3.12/dist-packages (from pydantic->fastf1) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic->fastf1) (0.4.2)
Requirement already satisfied: msgpack==1.1.2 in /usr/local/lib/python3.12/dist-packages (from signalrcore->fastf1) (1.1.2)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=1.12->cryptography->fastf1) (3.0)
Downloading fastf1-3.8.1-py3-none-any.whl (135 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 135.5/135.5 kB 4.4 MB/s eta 0:00:00
Downloading requests_cache-1.3.1-py3-none-any.whl (70 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 70.2/70.2 kB 6.3 MB/s eta 0:00:00
Downloading timple-0.1.8-py3-none-any.whl (17 kB)
Downloading rapidfuzz-3.14.3-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (3.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 49.7 MB/s eta 0:00:00a 0:00:01
Downloading signalrcore-1.0.2-py3-none-any.whl (55 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 55.6/55.6 kB 4.9 MB/s eta 0:00:00
Downloading cattrs-26.1.0-py3-none-any.whl (73 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 73.1/73.1 kB 7.0 MB/s eta 0:00:00
Downloading url_normalize-2.2.1-py3-none-any.whl (14 kB)
Installing collected packages: url-normalize, signalrcore, rapidfuzz, cattrs, requests-cache, timple, fastf1
Successfully installed cattrs-26.1.0 fastf1-3.8.1 rapidfuzz-3.14.3 requests-cache-1.3.1 signalrcore-1.0.2 timple-0.1.8 url-normalize-2.2.1

In [2]:
import fastf1

In [3]:
schedule = fastf1.get_event_schedule(2024)

req         WARNING 	DEFAULT CACHE ENABLED! (24.0 KB) /root/.cache/fastf1
WARNING:fastf1.fastf1.req:DEFAULT CACHE ENABLED! (24.0 KB) /root/.cache/fastf1

In [4]:
schedule

,RoundNumber,Country,Location,OfficialEventName,EventDate,EventName,EventFormat,Session1,Session1Date,Session1DateUtc,...,Session3,Session3Date,Session3DateUtc,Session4,Session4Date,Session4DateUtc,Session5,Session5Date,Session5DateUtc,F1ApiSupport
0,0,Bahrain,Sakhir,FORMULA 1 ARAMCO PRE-SEASON TESTING 2024,2024-02-23,Pre-Season Testing,testing,Practice 1,2024-02-21 10:00:00+03:00,2024-02-21 07:00:00,...,Practice 3,2024-02-23 10:00:00+03:00,2024-02-23 07:00:00,None,NaT,NaT,None,NaT,NaT,True
1,1,Bahrain,Sakhir,FORMULA 1 GULF AIR BAHRAIN GRAND PRIX 2024,2024-03-02,Bahrain Grand Prix,conventional,Practice 1,2024-02-29 14:30:00+03:00,2024-02-29 11:30:00,...,Practice 3,2024-03-01 15:30:00+03:00,2024-03-01 12:30:00,Qualifying,2024-03-01 19:00:00+03:00,2024-03-01 16:00:00,Race,2024-03-02 18:00:00+03:00,2024-03-02 15:00:00,True
2,2,Saudi Arabia,Jeddah,FORMULA 1 STC SAUDI ARABIAN GRAND PRIX 2024,2024-03-09,Saudi Arabian Grand Prix,conventional,Practice 1,2024-03-07 16:30:00+03:00,2024-03-07 13:30:00,...,Practice 3,2024-03-08 16:30:00+03:00,2024-03-08 13:30:00,Qualifying,2024-03-08 20:00:00+03:00,2024-03-08 17:00:00,Race,2024-03-09 20:00:00+03:00,2024-03-09 17:00:00,True
3,3,Australia,Melbourne,FORMULA 1 ROLEX AUSTRALIAN GRAND PRIX 2024,2024-03-24,Australian Grand Prix,conventional,Practice 1,2024-03-22 12:30:00+11:00,2024-03-22 01:30:00,...,Practice 3,2024-03-23 12:30:00+11:00,2024-03-23 01:30:00,Qualifying,2024-03-23 16:00:00+11:00,2024-03-23 05:00:00,Race,2024-03-24 15:00:00+11:00,2024-03-24 04:00:00,True
4,4,Japan,Suzuka,FORMULA 1 MSC CRUISES JAPANESE GRAND PRIX 2024,2024-04-07,Japanese Grand Prix,conventional,Practice 1,2024-04-05 11:30:00+09:00,2024-04-05 02:30:00,...,Practice 3,2024-04-06 11:30:00+09:00,2024-04-06 02:30:00,Qualifying,2024-04-06 15:00:00+09:00,2024-04-06 06:00:00,Race,2024-04-07 14:00:00+09:00,2024-04-07 05:00:00,True
5,5,China,Shanghai,FORMULA 1 LENOVO CHINESE GRAND PRIX 2024,2024-04-21,Chinese Grand Prix,sprint_qualifying,Practice 1,2024-04-19 11:30:00+08:00,2024-04-19 03:30:00,...,Sprint,2024-04-20 11:00:00+08:00,2024-04-20 03:00:00,Qualifying,2024-04-20 15:00:00+08:00,2024-04-20 07:00:00,Race,2024-04-21 15:00:00+08:00,2024-04-21 07:00:00,True
6,6,United States,Miami,FORMULA 1 CRYPTO.COM MIAMI GRAND PRIX 2024,2024-05-05,Miami Grand Prix,sprint_qualifying,Practice 1,2024-05-03 12:30:00-04:00,2024-05-03 16:30:00,...,Sprint,2024-05-04 12:00:00-04:00,2024-05-04 16:00:00,Qualifying,2024-05-04 16:00:00-04:00,2024-05-04 20:00:00,Race,2024-05-05 16:00:00-04:00,2024-05-05 20:00:00,True
7,7,Italy,Imola,FORMULA 1 MSC CRUISES GRAN PREMIO DEL MADE IN ...,2024-05-19,Emilia Romagna Grand Prix,conventional,Practice 1,2024-05-17 13:30:00+02:00,2024-05-17 11:30:00,...,Practice 3,2024-05-18 12:30:00+02:00,2024-05-18 10:30:00,Qualifying,2024-05-18 16:00:00+02:00,2024-05-18 14:00:00,Race,2024-05-19 15:00:00+02:00,2024-05-19 13:00:00,True
8,8,Monaco,Monaco,FORMULA 1 GRAND PRIX DE MONACO 2024,2024-05-26,Monaco Grand Prix,conventional,Practice 1,2024-05-24 13:30:00+02:00,2024-05-24 11:30:00,...,Practice 3,2024-05-25 12:30:00+02:00,2024-05-25 10:30:00,Qualifying,2024-05-25 16:00:00+02:00,2024-05-25 14:00:00,Race,2024-05-26 15:00:00+02:00,2024-05-26 13:00:00,True
9,9,Canada,Montréal,FORMULA 1 AWS GRAND PRIX DU CANADA 2024,2024-06-09,Canadian Grand Prix,conventional,Practice 1,2024-06-07 13:30:00-04:00,2024-06-07 17:30:00,...,Practice 3,2024-06-08 12:30:00-04:00,2024-06-08 16:30:00,Qualifying,2024-06-08 16:00:00-04:00,2024-06-08 20:00:00,Race,2024-06-09 14:00:00-04:00,2024-06-09 18:00:00,True
10,10,Spain,Barcelona,FORMULA 1 ARAMCO GRAN PREMIO DE ESPAÑA 2024,2024-06-23,Spanish Grand Prix,conventional,Practice 1,2024-06-21 13:30:00+02:00,2024-06-21 11:30:00,...,Practice 3,2024-06-22 12:30:00+02:00,2024-06-22 10:30:00,Qualifying,2024-06-22 16:00:00+02:00,2024-06-22 14:00:00,Race,2024-06-23 15:00:00+02:00,2024-06-23 13:00:00,True
11,11,Austria,Spielberg,FORMULA 1 QATAR AIRWAYS AUSTRIAN GRAND PRIX 2024,2024-06-30,Austrian Grand Prix,sprint_qualifying,Practice 1,2024-06-28 12:30:00+02:00,2024-06-28 10:30:00,...,Sprint,2024-06-29 12:00:00+02:00,2024-06-29 10:00:00,Qualifying,2024-06-29 16:00:00+02:00,2024-06-29 14:00:00,Race,2024-06-30 15:00:00+02:00,2024-06-30 13:00:00,True
12,12,United Kingdom,Silverstone,FORMULA 1 QATAR AIRWAYS BRITISH GRAND PRIX 2024,2024-07-07,British Grand Prix,conventional,Practice 1,2024-07-05 12:30:00+01:00,2024-07-05 11:30:00,...,Practice 3,2024-07-06 11:30:00+01:00,2024-07-06 10:30:00,Qualifying,2024-07-06 15:00:00+01:00,2024-07-06 14:00:00,Race,2024-07-07 15:00:00+01:00,2024-07-07 14:00:00,True
13,13,Hungary,Budapest,FORMULA 1 HUNGARIAN GRAND PRIX 2024,2024-07-21,Hungarian Grand Prix,conventional,Practice 1,2024-07-19 13:30:00+02:00,2024-07-19 11:30:00,...,Practice 3,2024-07-20 12:30:00+02:00,2024-07-20 10:30:00,Qualifying,2024-07-20 16:00:00+02:00,2024-07-20 14:00:00,Race,2024-07-21 15:00:00+02:00,2024-07-21 13:00:00,True
14,14,Belgium,Spa-Francorchamps,FORMULA 1 ROLEX BELGIAN GRAND PRIX 2024,2024-07-28,Belgian Grand Prix,conventional,Practice 1,2024-07-26 13:30:00+02:00,2024-07-26 11:30:00,...,Practice 3,2024-07-27 12:30:00+02:00,2024-07-27 10:30:00,Qualifying,2024-07-27 16:00:00+02:00,2024-07-27 14:00:00,Race,2024-07-28 15:00:00+02:00,2024-07-28 13:00:00,True
15,15,Netherlands,Zandvoort,FORMULA 1 HEINEKEN DUTCH GRAND PRIX 2024,2024-08-25,Dutch Grand Prix,conventional,Practice 1,2024-08-23 12:30:00+02:00,2024-08-23 10:30:00,...,Practice 3,2024-08-24 11:30:00+02:00,2024-08-24 09:30:00,Qualifying,2024-08-24 15:00:00+02:00,2024-08-24 13:00:00,Race,2024-08-25 15:00:00+02:00,2024-08-25 13:00:00,True
16,16,Italy,Monza,FORMULA 1 PIRELLI GRAN PREMIO D’ITALIA 2024,2024-09-01,Italian Grand Prix,conventional,Practice 1,2024-08-30 13:30:00+02:00,2024-08-30 11:30:00,...,Practice 3,2024-08-31 12:30:00+02:00,2024-08-31 10:30:00,Qualifying,2024-08-31 16:00:00+02:00,2024-08-31 14:00:00,Race,2024-09-01 15:00:00+02:00,2024-09-01 13:00:00,True
17,17,Azerbaijan,Baku,FORMULA 1 QATAR AIRWAYS AZERBAIJAN GRAND PRIX ...,2024-09-15,Azerbaijan Grand Prix,conventional,Practice 1,2024-09-13 13:30:00+04:00,2024-09-13 09:30:00,...,Practice 3,2024-09-14 12:30:00+04:00,2024-09-14 08:30:00,Qualifying,2024-09-14 16:00:00+04:00,2024-09-14 12:00:00,Race,2024-09-15 15:00:00+04:00,2024-09-15 11:00:00,True
18,18,Singapore,Marina Bay,FORMULA 1 SINGAPORE AIRLINES SINGAPORE GRAND P...,2024-09-22,Singapore Grand Prix,conventional,Practice 1,2024-09-20 17:30:00+08:00,2024-09-20 09:30:00,...,Practice 3,2024-09-21 17:30:00+08:00,2024-09-21 09:30:00,Qualifying,2024-09-21 21:00:00+08:00,2024-09-21 13:00:00,Race,2024-09-22 20:00:00+08:00,2024-09-22 12:00:00,True
19,19,United States,Austin,FORMULA 1 PIRELLI UNITED STATES GRAND PRIX 2024,2024-10-20,United States Grand Prix,sprint_qualifying,Practice 1,2024-10-18 12:30:00-05:00,2024-10-18 17:30:00,...,Sprint,2024-10-19 13:00:00-05:00,2024-10-19 18:00:00,Qualifying,2024-10-19 17:00:00-05:00,2024-10-19 22:00:00,Race,2024-10-20 14:00:00-05:00,2024-10-20 19:00:00,True
20,20,Mexico,Mexico City,FORMULA 1 GRAN PREMIO DE LA CIUDAD DE MÉXICO 2024,2024-10-27,Mexico City Grand Prix,conventional,Practice 1,2024-10-25 12:30:00-06:00,2024-10-25 18:30:00,...,Practice 3,2024-10-26 11:30:00-06:00,2024-10-26 17:30:00,Qualifying,2024-10-26 15:00:00-06:00,2024-10-26 21:00:00,Race,2024-10-27 14:00:00-06:00,2024-10-27 20:00:00,True
21,21,Brazil,São Paulo,FORMULA 1 LENOVO GRANDE PRÊMIO DE SÃO PAULO 2024,2024-11-03,São Paulo Grand Prix,sprint_qualifying,Practice 1,2024-11-01 11:30:00-03:00,2024-11-01 14:30:00,...,Sprint,2024-11-02 11:00:00-03:00,2024-11-02 14:00:00,Qualifying,2024-11-03 07:30:00-03:00,2024-11-03 10:30:00,Race,2024-11-03 12:30:00-03:00,2024-11-03 15:30:00,True
22,22,United States,Las Vegas,FORMULA 1 HEINEKEN SILVER LAS VEGAS GRAND PRIX...,2024-11-23,Las Vegas Grand Prix,conventional,Practice 1,2024-11-21 18:30:00-08:00,2024-11-22 02:30:00,...,Practice 3,2024-11-22 18:30:00-08:00,2024-11-23 02:30:00,Qualifying,2024-11-22 22:00:00-08:00,2024-11-23 06:00:00,Race,2024-11-23 22:00:00-08:00,2024-11-24 06:00:00,True
23,23,Qatar,Lusail,FORMULA 1 QATAR AIRWAYS QATAR GRAND PRIX 2024,2024-12-01,Qatar Grand Prix,sprint_qualifying,Practice 1,2024-11-29 16:30:00+03:00,2024-11-29 13:30:00,...,Sprint,2024-11-30 17:00:00+03:00,2024-11-30 14:00:00,Qualifying,2024-11-30 21:00:00+03:00,2024-11-30 18:00:00,Race,2024-12-01 19:00:00+03:00,2024-12-01 16:00:00,True
24,24,United Arab Emirates,Yas Island,FORMULA 1 ETIHAD AIRWAYS ABU DHABI GRAND PRIX ...,2024-12-08,Abu Dhabi Grand Prix,conventional,Practice 1,2024-12-06 13:30:00+04:00,2024-12-06 09:30:00,...,Practice 3,2024-12-07 14:30:00+04:00,2024-12-07 10:30:00,Qualifying,2024-12-07 18:00:00+04:00,2024-12-07 14:00:00,Race,2024-12-08 17:00:00+04:00,2024-12-08 13:00:00,True

In [6]:
schedule['EventFormat']

0               testing
1          conventional
2          conventional
3          conventional
4          conventional
5     sprint_qualifying
6     sprint_qualifying
7          conventional
8          conventional
9          conventional
10         conventional
11    sprint_qualifying
12         conventional
13         conventional
14         conventional
15         conventional
16         conventional
17         conventional
18         conventional
19    sprint_qualifying
20         conventional
21    sprint_qualifying
22         conventional
23    sprint_qualifying
24         conventional
Name: EventFormat, dtype: object

In [7]:
schedule['conventional']

KeyError: 'conventional'